// Auth
export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

// Chatroom
export const CREATE_CHATROOM = 'CREATE_CHATROOM';
export const DELETE_CHATROOM = 'DELETE_CHATROOM';
export const GET_CHATROOM = 'GET_CHATROOM';
export const GET_CHATROOM_USERS = 'GET_CHATROOM_USERS';
export const SET_CHATROOMS = 'SET_CHATROOMS';
export const SET_CHATROOM_INVITES = 'SET_CHATROOM_INVITES';
export const CLEAR_CHATROOM = 'CLEAR_CHATROOM';

// Category
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
// export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_CHATROOM_CATEGORIES = 'SET_CHATROOM_CATEGORIES';

// Channels 
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';
export const SET_CHANNEL = 'SET_CHANNEL';
export const SET_CHANNELS = 'SET_CHANNELS';
export const UNSET_CHANNEL = 'UNSET_CHANNEL';

// Comments
export const CREATE_CHANNEL_COMMENT = 'CREATE_CHANNEL_COMMENT';
export const DELETE_CHANNEL_COMMENT = 'DELETE_CHANNEL_COMMENT';
export const SET_COMMENTS = 'SET_COMMENTS';

// User
export const CREATE_DIRECT_MESSAGE = 'CREATE_DIRECT_MESSAGE';
export const DELETE_DIRECT_MESSAGE = 'DELETE_DIRECT_MESSAGE';
export const DELETE_DIRECT_MESSAGE_CHAT = 'DELETE_DIRECT_MESSAGE_CHAT';

export const JOIN_CHATROOM = 'JOIN_CHATROOM';
export const INVITE_CHATROOM = 'INVITE_CHATROOM';
export const LEAVE_CHATROOM = 'LEAVE_CHATROOM';

export const ADD_FRIEND = 'ADD_FRIEND';
export const SET_FRIENDS = 'SET_FRIENDS';
export const ACCEPT_FRIEND = 'ACCEPT_FRIEND';
export const REJECT_FRIEND = 'REJECT_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';

export const SET_HOME_VIEW = 'SET_HOME_VIEW';
export const SET_DIRECT_MESSAGES_REFERENCE = 'SET_DIRECT_MESSAGES_REFERENCE';
export const GET_REFERENCE = 'GET_REFERENCE';
export const SET_COMMENTS_HOME = 'SET_COMMENTS_HOME';
