// Auth
export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

// Chatroom
export const CREATE_CHATROOM = 'CREATE_CHATROOM';
export const DELETE_CHATROOM = 'DELETE_CHATROOM';
export const GET_CHATROOM = 'GET_CHATROOM';
export const CLEAR_CHATROOM = 'CLEAR_CHATROOM';
export const GET_CHATROOMS = 'GET_CHATROOMS';

// Category
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
// export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const GET_CHATROOM_CATEGORIES = 'GET_CHATROOM_CATEGORIES';

// Channels 
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const DELETE_CHANNEL = 'DELETE_CHANNEL';
export const GET_CHATROOM_CHANNELS = 'GET_CHATROOM_CHANNELS';
export const SET_CHANNEL = 'SET_CHANNEL';
export const UNSET_CHANNEL = 'UNSET_CHANNEL';

// Comments
export const CREATE_CHANNEL_COMMENT = 'CREATE_CHANNEL_COMMENT';
export const DELETE_CHANNEL_COMMENT = 'DELETE_CHANNEL_COMMENT';
export const GET_CHANNEL_COMMENTS = 'GET_CHANNEL_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';

// User
export const CREATE_DIRECT_MESSAGE = 'CREATE_DIRECT_MESSAGE';
export const DELETE_DIRECT_MESSAGE = 'DELETE_DIRECT_MESSAGE';
export const DELETE_DIRECT_MESSAGE_CHAT = 'DELETE_DIRECT_MESSAGE_CHAT';

export const JOIN_CHATROOM = 'JOIN_CHATROOM';
export const LEAVE_CHATROOM = 'LEAVE_CHATROOM';

export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';

export const SET_HOME_VIEW = 'SET_HOME_VIEW';
export const DISPLAY_DIRECT_MESSAGES = 'DISPLAY_DIRECT_MESSAGES';
export const SET_DIRECT_MESSAGES_REFERENCE = 'SET_DIRECT_MESSAGES_REFERENCE';
export const GET_REFERENCE = 'GET_REFERENCE';
export const SET_COMMENTS_HOME = 'SET_COMMENTS_HOME';
